### ISSUE TITLE
Todo 

### ISSUE THREAD

**Issue by asika32764** [lyrasoft/portal#5]
- [x] Report Test success|failure
    - [x] Add Report message
- [x] Login with GitHub and auth
- [x] Remove builds when PR closed or merged
    - [x] Re-build if re-opend
- [x] Remove builds when branch deleted
- [x] Auto add webhook if pipeline added
- [x] Repos list field
- [x] Config 
    - [x] Pipeline config
    - [x] Global config

**Comment by asika32764** [comment]
- [ ] Comment to review
- [ ] Can not login with GitHub Normally
- [ ] Modal issue with Angle
